import type { Metadata } from "next";
import { Geist_Mono, Sofia_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from 'react-hot-toast';
import Navbar from "@/components/common/Navbar";
import ReactQueryProvider from "@/components/ReactQueryProvider";

const sofiaSans = Sofia_Sans({
  variable: "--font-sofia-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  authModal 
}: Readonly<{
  children: React.ReactNode;
  authModal : React.ReactNode,
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={`${sofiaSans.variable} ${geistMono.variable} font-sans antialiased`}
      >
        <ThemeProvider 
        attribute="class"
        defaultTheme="light"
        
        
        >
          <ReactQueryProvider>

          
          
        <SessionProvider>
          <Navbar />
          {authModal}
          {children}
          <Toaster />
  
        </SessionProvider>

        </ReactQueryProvider>

        
        </ThemeProvider>
      </body>

      
    </html>
  );
}
